apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: guestbook
spec:
  host: guestbook.apps.cluster-jqm7c.jqm7c.sandbox1873.opentlc.com
  port:
    targetPort: 80
  to:
    kind: Service
    name: guestbook
    weight: 100
